### ISSUE TITLE
"Failed to execute script main"

### ISSUE THREAD

**Issue by Wallvon** [MM-coder/coronavirus-wallpaper#1]
Hi,

when I try to start the application it gives me
```py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\mmbus\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "gui.py", line 45, in <module>
  File "config.py", line 4, in load_option_from_config
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[7360] Failed to execute script main
```
I hope you can fix this asap, so I can use your application.

Thanks,
Robert S.

**Comment by MM-coder** [comment]
Fixed in v.1.1
