### ISSUE TITLE
Help -> About

### ISSUE THREAD

**Issue by Wallvon** [MM-coder/coronavirus-wallpaper#2]
Hi,

when I try to go to Help -> About I get

```py
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "gui.py", line 18, in about
  File "site-packages\PIL\Image.py", line 2809, in open
FileNotFoundError: [Errno 2] No such file or directory: 'img/mark.png'
```

Thanks,
Robert S.

**Comment by MM-coder** [comment]
Fixed in v1.2

**Comment by MM-coder** [comment]
@all-contributors please add @Wallvon for issues

**Comment by MM-coder** [comment]
@all-contributors please add @Wallvon for review

**Comment by MM-coder** [comment]
@all-contributors please add @MM-coder for code
